### ISSUE TITLE
Gaussian blur missing file?

### ISSUE THREAD

**Issue by einsweniger** [dasmysh/viscom_framework_enh#2]
https://github.com/dasmysh/viscom_framework_enh/blob/91df0ad67e44a5800e568ff9cd4f840b98597e01/src/enh/gfx/postprocessing/GaussianBlur.cpp#L20
this is missing from the sources, not sure if intended.

**Comment by einsweniger** [comment]
and some more, I guess there should be a `tm` folder :D
https://github.com/dasmysh/viscom_framework_enh/blob/91df0ad67e44a5800e568ff9cd4f840b98597e01/src/enh/gfx/postprocessing/FilmicTMOperator.cpp#L19
https://github.com/dasmysh/viscom_framework_enh/blob/91df0ad67e44a5800e568ff9cd4f840b98597e01/src/enh/gfx/postprocessing/BloomEffect.cpp#L17

**Comment by dasmysh** [comment]
Solved several commits ago.
